packages:
  - demos/*
allowBuilds:
  cbor-extract: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - eve@0.66.3
  - '@ai-sdk/gateway@4.0.92'
  - 'ai@7.0.114'
