packages:
  - demos/*
allowBuilds:
  cbor-extract: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - eve@0.27.12
  - '@platformatic/basic@3.60.0'
  - '@platformatic/foundation@3.60.0'
  - '@platformatic/globals@3.60.0'
  - '@platformatic/itc@3.60.0'
  - '@platformatic/metrics@3.60.0'
  - '@platformatic/telemetry@3.60.0'
  - '@platformatic/eve@0.1.0'
